apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: felipeamendes/multi-worker
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "1.5Gi"
            cpu: "1"
        env:
        - name: REDIS_HOST
          value: redis-service

        - name: REDIS_PORT
          value: "6379"
